name: Build Product1
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - product1/**
      - .github/actions/**
      - .github/workflows/product1.yml
  pull_request:
    paths:
      - product1/**
      - .github/actions/**
      - .github/workflows/product1.yml

jobs:
  generate_matrix:
    name: generate_matrix
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: shard
      uses: ./.github/actions/shard
    outputs:
      shards: ${{ steps.shard.outputs.shards }}

  build:
    name: hello
    needs: [generate_matrix]
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shards: ${{ fromJson(needs.generate_matrix.outputs.shards) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Product Image
        uses: ./.github/actions/build
        with:
          product: product1 # todo: how to handle workflow_dispatch (use product input)
      - run: echo ${{ matrix.shards }}
      - name: Publish Product Image
        uses: ./.github/actions/publish
        with:
          product: product1
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          harbor_secret: ${{ secrets.HARBOR_ROBOT_SDP_GITHUB_ACTION_BUILD_SECRET }}
