name: Build Product1
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - product1/**
      - .github/**
  pull_request:
    paths:
      - product1/**
      - .github/**

jobs:
  build:
    name: hello
    # permissions:
    #   id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Product Image
        uses: ./.github/actions/build
        with:
          product: product1 # todo: how to handle workflow_dispatch (use product input)
          nexus_password: ${{ secrets.NEXUS_PASSWORD }}
          harbor_secret: ${{ secrets.HARBOR_ROBOT_SDP_GITHUB_ACTION_BUILD_SECRET }}
      - name: Publish Product Image
        uses: ./.github/actions/publish
