name: Build Product1
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - product1/**
      - .github/**
  pull_request:
    paths:
      - product1/**
      - .github/**

jobs:
  build:
    name: hello
    # permissions:
    #   id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: ./.github/actions/build
        with:
          product: product1 # todo: how to handle workflow_dispatch (use product input)
