---
name: Build Product1

env:
  PRODUCT_NAME: product1

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - product1/**
      - .github/actions/**
      - .github/workflows/dev_product1.yaml
  pull_request:
    paths:
      - product1/**
      - .github/**

jobs:
  generate_matrix:
    name: Generate Version List
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: shard
        uses: stackabletech/actions/shard@4bfd3b65f22af597fe784599c077dc34bf5894a7 # v0.8.0
        with:
          product-name: ${{ env.PRODUCT_NAME }}
    outputs:
      versions: ${{ steps.shard.outputs.versions }}

  build:
    name: Build/Publish ${{ matrix.versions }}-${{ matrix.runner.arch }} Image
    needs: [generate_matrix]
    permissions:
      id-token: write
    runs-on: ${{ matrix.runner.name }}
    strategy:
      matrix:
        runner:
          - {name: "ubuntu-latest", arch: "amd64"}
          - {name: "ubicloud-standard-8-arm", arch: "arm64"}
        versions: ${{ fromJson(needs.generate_matrix.outputs.versions) }}
    steps:
      - name: Fail on purpose
        if: github.run_attempt <= 2
        shell: bash
        run: |
          exit 1

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build Product Container Image
        id: build
        uses: stackabletech/actions/build-product-image@4bfd3b65f22af597fe784599c077dc34bf5894a7 # v0.8.0
        with:
          product-name: ${{ env.PRODUCT_NAME }}
          product-version: ${{ matrix.versions }}

      - name: Publish Container Image on oci.stackable.tech
        uses: stackabletech/actions/publish-image@4bfd3b65f22af597fe784599c077dc34bf5894a7 # v0.8.0
        with:
          image-registry-uri: oci.stackable.tech
          image-registry-username: robot$sdp+github-action-build
          image-registry-password: ${{ secrets.HARBOR_ROBOT_SDP_GITHUB_ACTION_BUILD_SECRET }}
          image-repository: sdp/${{ env.PRODUCT_NAME }}
          image-manifest-tag: ${{ steps.build.outputs.image-manifest-tag }}
          source-image-uri: localhost/${{ env.PRODUCT_NAME }}:${{ steps.build.outputs.image-manifest-tag }}

  publish_manifests:
    name: Build/Publish ${{ matrix.versions }} Index Manifest
    needs: [generate_matrix, build]
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: ${{ fromJson(needs.generate_matrix.outputs.versions) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Publish and Sign Image Index Manifest to oci.stackable.tech
        uses: stackabletech/actions/publish-index-manifest@4bfd3b65f22af597fe784599c077dc34bf5894a7 # v0.8.0
        with:
          image-registry-uri: oci.stackable.tech
          image-registry-username: robot$sdp+github-action-build
          image-registry-password: ${{ secrets.HARBOR_ROBOT_SDP_GITHUB_ACTION_BUILD_SECRET }}
          image-repository: sdp/${{ env.PRODUCT_NAME }}
          image-index-manifest-tag: ${{ matrix.versions }}-stackable0.0.0-dev

  notify:
    name: Failure Notification
    needs: [generate_matrix, build, publish_manifests]
    runs-on: ubuntu-latest
    if: failure() || github.run_attempt > 1
    steps:
      - name: Send Notification
        uses: stackabletech/actions/send-slack-notification@feat/failure-success-notifications
        with:
          build-result: ${{ needs.build.result }}
          publish-manifests-result: ${{ needs.publish_manifests.result }}
          slack-token: ${{ secrets.SLACK_CONTAINER_IMAGE_TOKEN }}
