name: Build (and optionally publish) 0.0.0-dev images
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: hello
    # permissions:
    #   id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
