---
name: Mirror Container Image
on:
  workflow_dispatch:
    inputs:
      image-repository-uri:
        description: |
          The image repository URI, like registry.k8s.io/git-sync/git-sync
        type: choice
        options:
          - registry.k8s.io/sig-storage/csi-node-driver-registrar
          - registry.k8s.io/sig-storage/csi-provisioner
          - registry.k8s.io/git-sync/git-sync
      image-index-manifest-tag:
        description: |
          The image index manifest tag, like 1.0.14
        type: string
        required: true

jobs:
  mirror-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Pull container image
        shell: bash
        env:
          IMAGE_INDEX_MANIFEST_TAG: ${{ inputs.image-index-manifest-tag }}
          IMAGE_REPOSITORY_URI: ${{ inputs.image-repository-uri }}
        run: |
          docker pull "$IMAGE_REPOSITORY_URI:$IMAGE_INDEX_MANIFEST_TAG" --platform amd64 --quiet
          docker pull "$IMAGE_REPOSITORY_URI:$IMAGE_INDEX_MANIFEST_TAG" --platform arm64 --quiet
