name: Build Product1
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: hello
    # permissions:
    #   id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        shell: bash
        run: | 
          sudo apt update
          sudo apt install -y python3

      - name: Run Python
        shell: bash
        run: python3 conf.py
