name: Sidequest

on:
  push:
    paths:
    - .github/workflows/sidequest.yml

jobs:
  gather_info:
    name: gather_info
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12' 
    - id: a
      shell: python
      run: |
        # Need to get the number of versions for the product
        import sys
        import os
        sys.path.append(str(os.getcwd()))
        import conf

        # get the product config
        product = list(filter(lambda x: x["name"] == "product2", conf.products))[0]
        # enumerate the versions and only keep the index, eg: [0, 1, 2]
        versions = [k for k,v in enumerate(product["versions"])]
        output = f"SHARDS={versions}"
        print(f"Writing to $GITHUB_OUTPUT: {output}")

        github_outputs_file = os.environ['GITHUB_OUTPUT']
        f = open(github_outputs_file, "w")
        f.write(output)
        f.close()
    outputs:
      shards: ${{ steps.a.outputs.SHARDS }}

  verify_output:
    needs: [gather_info]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.gather_info.outputs.shards }}

  run_matrix:
    needs: [gather_info]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: ${{ fromJson(needs.gather_info.outputs.shards) }}
    steps:
      - run: echo doing shard ${{ matrix.shard }}
