name: Sidequest2

on:
  push:
    paths:
    - .github/workflows/sidequest2.yml

jobs:
  test:
    name: Run Integration Test
    runs-on: ubuntu-latest
    # services:
    #   otel-collector:
    #     image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s:0.131.1
    #     options: >-
    #       --config=/mnt/config
    #     env:
    #       # Can we specify a config path here?
    #       A: B
    #     volumes:
    #       # TODO: Mount a volume with the collector config
    #       # TODO: Mount a volume with the kuttl output files. Use a Temp dir so it is available before the checkout happens
    #       #   - .:/mnt
    #       - /home/runner/work/_actions/actions/stackabletech/run-integration-test/
    steps:
      - run: |
          set -x
          set +e
          ls -al /home/runner/work/
          ls -al /home/runner/work/_temp/
          ls -al /home/runner/work/dummy-docker-images/
          ls -al /home/runner/work/dummy-docker-images/dummy-docker-images
          ls -al /home/runner/work/_actions/
          ls -al /home/runner/work/_actions/stackabletech/
          ls -al /home/runner/work/_actions/stackabletech/actions/
          ls -al /home/runner/work/_actions/stackabletech/actions/48f987367d0cb42db1248d050faabcdf26218f1e/
          ls -al /home/runner/work/_actions/stackabletech/actions/48f987367d0cb42db1248d050faabcdf26218f1e/run-integration-test/
          exit 0

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
          submodules: recursive

      - name: Run Integration Test
        id: test
        uses: stackabletech/actions/run-integration-test@48f987367d0cb42db1248d050faabcdf26218f1e # TODO: Use released version
        with:
          replicated-api-token: nope
          test-mode-input: a
          test-suite: b
          test-mode: c
          test: d
